config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :bookings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions:"sessions"}, path: 'u', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users

  

  get 'contact', to: 'static_pages#contact'

  get 'about-us', to: 'static_pages#about'

  get 'home', to: 'static_pages#home'


  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all
  skip_before_action :authenticate_user!, :only => [:show, :new, :edit, :create, :update]

  # GET /bookings
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
      ExampleMailer.booking_email.deliver
    else
      render :new
    end
  end

  # PATCH/PUT /bookings/1
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.require(:booking).permit(:first_name, :middle_name, :last_name, :email, :phone_number, :comment)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Booking</div>
      <div class="card-body">
           <%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-6">
    
 <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :booking_first_name ,class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, id: :booking_middle_name,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :booking_last_name,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :booking_email,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :booking_phone_number,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :booking_comment,class: 'form-control' %>
  </div>


  </div>
  <div class="col-md-2"></div>
</div>



 
 <div class="row">
    <div class="col-md-6"></div>

  <div class="form-group">
    <%= form.submit "Create Booking", class: 'btn btn-primary btn-block' %>
  </div>
<% end %>



                     </div>
             </div>

         </div>
 </div>
      

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<div class="container">
    <div class="card card-login mx-auto mt-5">
     
      <div class="card-body">

<p id="notice"><%= notice %></p>

<h1>Bookings</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.first_name %></td>
        <td><%= booking.middle_name %></td>
        <td><%= booking.last_name %></td>
        <td><%= booking.email %></td>
        <td><%= booking.phone_number %></td>
        <td><%= booking.comment %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Booking', new_booking_path %>


</div>
</div>
</div>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Booking</div>
      <div class="card-body">

<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @booking.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @booking.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @booking.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @booking.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @booking.phone_number %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @booking.comment %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Home', root_path %>

</div>

</div>

</div>