config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :bookings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions:"sessions"}, path: 'u', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users

  

  get 'contact', to: 'static_pages#contact'

  get 'about-us', to: 'static_pages#about'

  get 'home', to: 'static_pages#home'


  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
      <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p><%= copyright_generator %></p>
      </footer>

app/views/shared/_application_nav.html.erb
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      
      <%= link_to "SpecsHubGh",  root_path ,{ :class=>"navbar-brand" }%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home",  root_path ,{ :class=>"nav-link" }%>
          </li>
          <li class="nav-item">
            <%= link_to "About",  about_us_path ,{ :class=>"nav-link" }%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact Us",  contact_path ,{ :class=>"nav-link" }%>
          </li>
          <li class="nav-item">
            <% if current_user.nil? %>
  <%= link_to new_user_session_path, class: 'nav-link' do %>Sign in<% end %>
<% else %>
<% if current_user.admin? %>
  <%= link_to new_appointment_path, class: 'nav-link' do %>Create Appointment<% end %>
<% end %>
<li class="nav-item">
  <%= link_to destroy_user_session_path, class: 'nav-link' do %>Logout <% end %>
</li>
<% end %>
          </li>
         
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>