config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :bookings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions:"sessions"}, path: 'u', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users

  

  get 'contact', to: 'static_pages#contact'

  get 'about-us', to: 'static_pages#about'

  get 'home', to: 'static_pages#home'


  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :time, presence: true


  after_create :reminder

  # Notify our appointment attendee X minutes before the appointment time
  def reminder
    @twilio_number = ENV['TWILIO_NUMBER']
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    
    @client = Twilio::REST::Client.new account_sid, ENV['TWILIO_AUTH_TOKEN']



    time_str = ((self.time).localtime).strftime("%I:%M%p on %b. %d, %Y")
    reminder = "Hi #{self.name}. Just a reminder that you have an appointment coming up at #{time_str}."
    message = @client.messages.create(
      :from => @twilio_number,
      :to => self.phone_number,
      :body => reminder,
    )
  end

  def when_to_run
    minutes_before_appointment = 1.minutes
    time - minutes_before_appointment
  end

  handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /appointments
  def index
    @appointments = Appointment.all
    if @appointments.length.zero?
      flash[:alert] = 'You have no appointments. Create one now to get started.'
    end
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to @appointment, notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /appointments/1
  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    redirect_to appointments_url, notice: 'Appointment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def find_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def appointment_params
      params.require(:appointment).permit(:name, :phone_number, :time, :time_zone)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Appointment</div>
      <div class="card-body">
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="col-md-2"></div>

  <div class="col-md-6">

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :appointment_name,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :appointment_phone_number,class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= form.label :time %>
    <div> 
           <%= time_select :appointment, :time, {:default => {:hour => '00', :minute => '00'}} %>
    </div>
    

    <div>
         <%= date_select :appointment, :time, :default=> Date.today %>
    </div>
    <div >
      <%= form.time_zone_select :time_zone, ActiveSupport::TimeZone.all.sort, default: "London" %>
    </div>
    
 </div>

  <div class="form-group">
   
    <%= form.submit "Create Appointment", class: 'btn btn-primary btn-block' %>
  </div>
<% end %>
 </div>
    </div>
       </div> 
           </div>



                </div>
      

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="container">
    <div class="card card-login mx-auto mt-5">
     
      <div class="card-body">

<p id="notice"><%= notice %></p>

<h1>Appointments</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.name %></td>
        <td><%= appointment.phone_number %></td>
        <td><%= appointment.time %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>


</div>
</div>
</div>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Appointment</div>
      <div class="card-body">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @appointment.phone_number %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

</div>

</div>
</div>